import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import TopHeader from "./_components/TopHeader";

const manrope = Manrope({
  variable: "--font-Manrope",
  subsets: ["latin"],
});

export const metadata = {
  title: "Survay Master",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.className} suppressHydrationWarning>
      <body>
        <header>
          <TopHeader />
          <Navbar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
